### ISSUE TITLE
v1 checklist

### ISSUE THREAD

**Issue by tabatkins** [foolip/spec-test-bot#83]
* [x] spec-test-bot can check spec commits for WPT links, and create a Commit Check from it
	* [ ] it checks all the WPT link variants (tracked in an inline TODO)
* [ ] stb can be talked to, to tell it to forget a WPT link it erroneously grabbed, or to give it a WPT link when the commit message forgot to list one
	* [ ] stb can update the Check accordingly

**Comment by foolip** [comment]
While GitHub Checks are always against a commit SHA, there are [two different kinds of checks](https://github.com/foolip/spec-test-bot/blob/main/docs/design.md#mockups) we could do, PR checks and commit checks. Should both of those be considered v1? It sort of depends on where we think this will be tried out first.

**Comment by tabatkins** [comment]
Yeah, if I'm going to try and connect it to CSSWG, we do most of our work outside of PRs, so the commit check is more useful. We def want to do PRs as well, but we want to then automatically pass the commit checks when the PR is merged, if the PR checks passed. That'll need the db backing.

So if v1 doesn't include the db, then I think we need to decide between commit and PR checks for now, and not do both.

**Comment by foolip** [comment]
So I'm thinking let's do only commit checks as a starting point then, that's more low-level than PRs and likely will result in reusable building blocks for PRs later.
